language: python
python:
  - 3.8 # use nodejs v12 LTS
branches:
  only:
    - master
before_install:
  - chmod +x ./*
  - git lfs install
  - sudo apt-get install -y jq
script:
  - bash -x run_src.sh https://$GH_BKUP_TOKEN@github.com/yindaheng98backup/backup-src master https://$GH_BKUP_TOKEN@github.com/yindaheng98backup/backup master
  - bash -x run_backup_to_tar.gz.sh yindaheng98 $GH_TOKEN https://$GH_BKUP_TOKEN@github.com/yindaheng98backup/backup backup_repo_pack
